export const configContentMap = new Map([
  ["tagNum", "设备标签号"],
  ["serialNo", "Tag No."],
  ["deviceName", "设备名称"],
  ["Name", "Name"],
  ["specsModel", "规格型号"],
  ["drawingNo", "图纸号/物料号"],
  ["deviceBelongUnit", "Mat.Cd."],
  ["factoryNo", "出厂编码"],
  ["device_category", "Fact.Cd."],
  ["shapeSize", "外形尺寸"],
  ["deviceWeight", "设备自重"],
  ["produceFactory", "生产厂家"],
  ["deviceStatus", "Supp"],
  ["factoryTime", "出厂时间"],
  ["devicePosition", "Prod.Dt."],
  ["devicePerson", "设备负责人"]
  // ["deviceName", "设备名称"],
  // ["Tag No.", "序列号"],
  // // ["tagNum", "设备标签号"],
  // ["specsModel", "规格型号"],
  // ["drawingNo", "图纸号/物料号"],
  // ["factoryNo", "出厂编码"],
  // ["serialNo", "SN码/序列码"],
  // ["shapeSize", "外形尺寸"],
  // ["deviceWeight", "设备自重"],
  // ["produceFactory", "生产厂家"],
  // ["factoryTime", "出厂时间"],
  // ["devicePerson", "设备负责人"],
  // ["Name", "设备责任单位"],
  // ["Mat.Cd.", "设备归属单位"],
  // ["Fact.Cd.", "设备类别"],
  // ["Prod.Dt.", "设备位置"],
  // ["Supp", "设备状态"]
]);
